default_agent: agent_with_memory
agents:
  agentcore_lang_runtime:
    name: agentcore_lang_runtime
    entrypoint: /Users/aumpatel/Documents/GitHub/TCS-Exploration/01_agentcore_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/aumpatel/Documents/GitHub/TCS-Exploration
    aws:
      execution_role: arn:aws:iam::711907671316:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-c980c3716d
      execution_role_auto_create: false
      account: '711907671316'
      region: us-east-1
      ecr_repository: 711907671316.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agentcore_lang_runtime
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_lang_runtime-TGJp8hGxqF
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:711907671316:runtime/agentcore_lang_runtime-TGJp8hGxqF
      agent_session_id: fec60f53-0bcf-47bc-aefb-6146ba529275
    codebuild:
      project_name: bedrock-agentcore-agentcore_lang_runtime-builder
      execution_role: arn:aws:iam::711907671316:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-c980c3716d
      source_bucket: bedrock-agentcore-codebuild-sources-711907671316-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  agent_with_memory:
    name: agent_with_memory
    entrypoint: /Users/aumpatel/Documents/GitHub/TCS-Exploration/02_agentcore_memory.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/aumpatel/Documents/GitHub/TCS-Exploration
    aws:
      execution_role: arn:aws:iam::711907671316:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-f3cb8b6d58
      execution_role_auto_create: false
      account: '711907671316'
      region: us-east-1
      ecr_repository: 711907671316.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agent_with_memory
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agent_with_memory-v3CrfzEDdU
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:711907671316:runtime/agent_with_memory-v3CrfzEDdU
      agent_session_id: 8e15ccd6-dc34-4097-a59f-0c94ff9a0a0b
    codebuild:
      project_name: bedrock-agentcore-agent_with_memory-builder
      execution_role: arn:aws:iam::711907671316:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-f3cb8b6d58
      source_bucket: bedrock-agentcore-codebuild-sources-711907671316-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: customer_care_agent_memory-bFHAQUAcdy
      memory_arn: null
      memory_name: agent_with_memory_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
